version: '3.1'
services:
  user_service:
    build:
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: user_service
    depends_on:
      - mongodb
    ports:
      - "3001:3000"
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: