version: '3.1'
services:
  user_service:
    image: node:18-alpine
    container_name: user_service
    depends_on:
      - mongodb
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install && npm start dev"

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: